version: '3.8'
services:
  app-node-service:
    build: .
    ports:
      - "81:81"  # Assuming SERVER_PORT is 81
    env_file:
      - .env  # Fixed typo
    depends_on:
      my-redis-container:
        condition: service_healthy
    networks:
      - app_networks

  my-redis-container:
    image: redis:7.4.0
    ports:
      - "6379:6379"  # Redis default port
    networks:
      - app_networks
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  app_networks:
    driver: bridge

volumes:
  redis_data:
